version: '3.7'
services:
  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    ports:
      - 3000:80
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      - ./uploads:/var/www/html/wp-content/uploads
      - ./plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: lkALm4N0WqK5xnpw
      WORDPRESS_TABLE_PREFIX: wp_eco_

  mysql:
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: lkALm4N0WqK5xnpw
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
  
  srd:
    build: ./docker/search-replace-db
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: lkALm4N0WqK5xnpw
      SEARCH: http://localhost/
      REPLACE: http://localhost:3000